force_keyboard_focus = true
selection_wrap = true
hide_action_hints = true

[placeholders]
"default" = { input = " Search...", list = "No Results" }

[keybinds]
quick_activate = []
next = ["Down", "ctrl n"]
previous = ["Up", "ctrl p"]

[columns]
symbols = 1

[providers]
max_results = 256
default = [
  "desktopapplications",
  "websearch",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[[emergencies]]
text = "Restart Walker"
command = "pkill walker"

[providers.actions]
desktopapplications = [
  { action = "pin", bind = "ctrl b", after = "AsyncReload" },
  { action = "unpin", bind = "ctrl u", after = "AsyncReload" },
  { action = "pinup", bind = "ctrl Up", after = "AsyncReload" },
  { action = "pindown", bind = "ctrl Down", after = "AsyncReload" }
]
