# Terminal
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(terminal-cwd)" tmux

# Browser
bindd = SUPER SHIFT, B, Browser, exec, launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, launch-browser --private

# File manager
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(terminal-cwd)"

# Applications
bindd = SUPER SHIFT, M, Music, exec, launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, uwsm-app -- xdg-terminal-exec -e ${EDITOR:-nvim}
bindd = SUPER SHIFT, D, Docker, exec, uwsm-app -- xdg-terminal-exec -e lazydocker
bindd = SUPER SHIFT, G, Signal, exec, launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# Web apps
bindd = SUPER SHIFT, A, Claude, exec, launch-webapp "https://claude.ai/"
bindd = SUPER SHIFT, Y, YouTube, exec, launch-webapp "https://youtube.com/"
