[ids]
0001:0001:09b4e68d

[main]
include common

# HHKB analogues
# Swap Backspace with the physical \| key.
backslash = backspace
backspace = backslash
capslock = control

capslock = overload(control, esc)

#Mac muscle memory: Flip alt and windows
leftcontrol = leftalt
leftalt = leftmeta
# leftcontrol = leftalt

# rightmeta = rightalt
rightalt = rightmeta
rightcontrol = rightalt
